Create setup docs
squanchy-dev/squanchy-android pull request #14
Opened 2016-12-03 16:50 UTC by rock3r

Add some instructions on how to set up the app from scratch.

2016-12-03 16:54 UTC, frapontillo requested changes
Just a minor annoyance.

2016-12-03 16:54 UTC, frapontillo commented on README.md
> +See `docs/setup.md`.
Add link

2016-12-04 10:25 UTC, rock3r commented
@frapontillo all yours

2016-12-04 10:28 UTC, frapontillo approved these changes

2016-12-04 10:40 UTC, merged