SQ-55/notification service
squanchy-dev/squanchy-android pull request #146
Opened 2017-03-19 11:36 UTC by danybony

This PR connects the existing notification system to the Favorite events repository.
To keep consistency with other modules of the app, the existing `NotificationService` has been renamed to `NotificationIntentService`, while `NotificationService` now is the service responsible of fetching favorite events.

2017-03-19 11:48 UTC, fourlastor requested changes
Few comments ✨

2017-03-19 11:48 UTC, fourlastor commented on app/src/main/java/net/squanchy/notification/NotificationCreator.java
> +    private String getPlaceName(Event event) {
This can also be done with

`event.place.map(place -> place.name).or(EMPTY_PLACE_NAME)`

2017-03-19 11:48 UTC, fourlastor commented on app/src/main/java/net/squanchy/notification/NotificationsIntentService.java
> +        notificationCreator = new NotificationCreator(this);
Shouldn't this go in the component? 😛

2017-03-19 11:48 UTC, fourlastor commented on app/src/main/java/net/squanchy/notification/NotificationsIntentService.java
> +                    .filter(event -> event.startTime().isAfter(now))
Instead of using rx operators, I'd rather have an observable of list and map and using `List.filter`

2017-03-19 11:48 UTC, fourlastor commented on app/src/main/java/net/squanchy/notification/NotificationsIntentService.java
> +        Log.d("xxx", "Next alarm for " + serviceAlarm.toString());
Use timber for logging 😛

2017-03-19 22:06 UTC, danybony commented on app/src/main/java/net/squanchy/notification/NotificationCreator.java
> +    private String getPlaceName(Event event) {
Yes, way better

2017-03-19 22:11 UTC, danybony commented on app/src/main/java/net/squanchy/notification/NotificationsIntentService.java
> +                    .filter(event -> event.startTime().isAfter(now))
Can do that, but why? What's the reason why you prefer that?

2017-03-20 09:04 UTC, danybony commented on app/src/main/java/net/squanchy/notification/NotificationCreator.java
> +    private String getPlaceName(Event event) {
Done in 5d3e3d6

2017-03-20 11:46 UTC, fourlastor commented on app/src/main/java/net/squanchy/notification/NotificationsIntentService.java
> +                    .filter(event -> event.startTime().isAfter(now))
Rx operators are to be used for streams, here the single atomic event should be a list of events, not a single event, so the transformation should be from list to list more than from event to event.

2017-03-20 16:00 UTC, danybony commented on app/src/main/java/net/squanchy/notification/NotificationsIntentService.java
> +                    .filter(event -> event.startTime().isAfter(now))
Done in 8f283c756b87df6cd4854d58cd94ef66096003e3

2017-03-20 16:18 UTC, fourlastor commented on app/src/main/java/net/squanchy/notification/NotificationModule.java
> +        return Notifier.from(context);
nitpick (not a blocker but maybe next PR?) `Notifier` should not have a `from` method and you should have the dependencies explicitly in this module :tongue:

2017-03-20 16:18 UTC, fourlastor approved these changes

2017-03-20 16:19 UTC, merged

2017-03-20 16:20 UTC, danybony commented on app/src/main/java/net/squanchy/notification/NotificationModule.java
> +        return Notifier.from(context);
True, good point!
I'll update it in the next PR