Add CI static analysis, address all outstanding warnings
squanchy-dev/squanchy-android pull request #294
Opened 2017-06-06 12:49 UTC by rock3r

We have now all the static analysis we might ever want!

 * PMD, Checkstyle and Findbugs for Java code
 * [Detekt](https://github.com/arturbosch/detekt) for Kotlin
 * Lint for Android-specific issues

And to make this all possible... **SURPRISE CI SWAP!**

We're now using [CircleCI](https://circleci.com/gh/squanchy-dev/squanchy-android) instead of Travis. Why?
 * Travis is _sloooooow_
   It took an average of 10 minutes on Travis to get a plain build, and with the static analysis this would've ballooned up to unbearable levels. CircleCI completes a static-analysis build in 1-3 minutes _less_ per build compared to Travis' "naked build" times
 * CircleCI looks good
    Look at that [build report](https://circleci.com/gh/squanchy-dev/squanchy-android/29) page! Nothing else to say ✨ 
 * I was curious to use CircleCI
   I heard great things about it, and I have to say, while not as flexible/configurable as a Jenkins issue, it's free, fast, flexible enough, and hassle-free. I count that as a win.
 * You can easily store test reports and build artifacts (including the static analysis report results)
    See an example [of JUnit test results](https://circleci.com/gh/squanchy-dev/squanchy-android/29#tests/containers/0) and of the [other reports](https://circleci.com/gh/squanchy-dev/squanchy-android/29#artifacts/containers/0) in a sample build.

Not _everything_ is 100% awesome; in particular, CircleCI only understands the JUnit test reports, but not the other tools', so you still have to fish those out manually. No nice report pages the way Jenkins can generate (yet?). But those are mostly minor things and I feel this is still a big step ahead in the right direction.

------

Note: this PR is big-ish because it contains a loooot of static analysis fixes, but most of them are very very trivial changes, so it shouldn't be _too_ big. I'm sorry I couldn't keep it smaller, but the build would never be green if I didn't address them all in one go.

2017-06-07 13:04 UTC, fourlastor requested changes
Few comments 💃 there's quite a lot of them because I left marker comments to be able to find the suppressions I want to remove

2017-06-07 13:04 UTC, fourlastor commented on app/src/main/java/net/squanchy/home/HomeActivity.java
> +                Timber.e("Unsupported proximity event: %s", proximityEvent);
warning?

2017-06-07 13:04 UTC, fourlastor commented on app/src/main/java/net/squanchy/home/HomeActivity.java
> +@SuppressWarnings({"PMD.ExcessiveImports", "PMD.GodClass"})           // Unfortunately this activity has got a lot to do
can we not add the suppress and increase the threshold? If we accidentally clean up this class it won't show up as a lower warning count otherwise

2017-06-07 13:04 UTC, fourlastor commented on app/src/main/java/net/squanchy/navigation/RoutingActivity.java
> +        subscriptions = new CompositeDisposable();
this should go in `onCreate`

2017-06-07 13:04 UTC, fourlastor commented on app/src/main/java/net/squanchy/navigation/RoutingActivity.java
> +        subscriptions.dispose();
this should be `clear()`

2017-06-07 13:04 UTC, fourlastor commented on app/src/main/java/net/squanchy/navigation/firststart/FirstStartWithNoNetworkActivity.java
> +@SuppressWarnings("PMD.ExcessiveImports")           // Might use some refactoring later on to extract some collaborator
same here, I rather have warnings so we know what we need to address

2017-06-07 13:04 UTC, fourlastor commented on app/src/main/java/net/squanchy/notification/NotificationsIntentService.java
> +        subscriptions = new CompositeDisposable();
this goes in `onCreate`, also I can't see the `subscriptions.clear()` in `onStop`

2017-06-07 13:04 UTC, fourlastor commented on app/src/main/java/net/squanchy/notification/NotificationsIntentService.java
> +            subscriptions.add(
should we clear the subscriptions before the if? which ones? Maybe it's worth having the notification subscriptions as a different `CompositeSubscription`

2017-06-07 13:04 UTC, fourlastor commented on app/src/main/java/net/squanchy/proximity/preconditions/ModularProximityPreconditions.java
> +    @SuppressWarnings("PMD.UseVarargs") // This array is passed to the Android APIs and is kept for consistency
well technically you don't need to use an array even when you have a varargs

2017-06-07 13:04 UTC, fourlastor commented on app/src/main/java/net/squanchy/schedule/domain/view/Event.kt
> +@Suppress("LongParameterList") // This is just a big model - TODO refactor this to split it up
remove the suppress and increase the threshold :P

2017-06-07 13:04 UTC, fourlastor commented on app/src/main/java/net/squanchy/schedule/view/ScheduleViewPagerAdapter.java
> +        return date.toString(TITLE_FORMAT_TEMPLATE).toUpperCase(Locale.getDefault());
in other places we use `Locale.US`, is this correct?

2017-06-07 13:04 UTC, fourlastor commented on app/src/main/java/net/squanchy/search/SearchActivity.java
> +@SuppressWarnings("PMD.ExcessiveImports")           // Might use some refactoring later on to extract some collaborator
remove the suppress and increase the threshold

2017-06-07 13:04 UTC, fourlastor commented on app/src/main/java/net/squanchy/speaker/domain/view/Speaker.kt
> +@Suppress("LongParameterList") // This is just a big model - TODO refactor this to split it up
increase the threshold

2017-06-07 13:04 UTC, fourlastor commented on app/src/main/java/net/squanchy/support/view/Hotspot.java
> +    @SuppressWarnings("PMD.ShortMethodName") // Cannot really do much, this is a coordinate value
hopefully will solve itself with kotlin data classes :D

2017-06-07 13:04 UTC, fourlastor commented on app/src/main/java/net/squanchy/support/widget/SpeakerView.java
> +    protected LayoutInflater layoutInflater() {
final

2017-06-07 13:04 UTC, fourlastor commented on app/src/main/java/net/squanchy/tweets/domain/view/TweetViewModel.kt
> +@Suppress("LongParameterList") // This is just a big model - TODO refactor this to split it up
increase the thresholds (I'm marking all them so it's easier to find them and see if we did all of them)

2017-06-07 13:04 UTC, fourlastor commented on circle.yml
> +        FABRIC_API_KEY: 0000000000000000000000000000000000000000
can you name this `DUMMY_FABRIC_API_KEY` as well?

2017-06-07 13:10 UTC, rock3r commented on app/src/main/java/net/squanchy/home/HomeActivity.java
> +@SuppressWarnings({"PMD.ExcessiveImports", "PMD.GodClass"})           // Unfortunately this activity has got a lot to do
I have in my TODO list to track these separately. I'd rather that than increasing the threshold, which might mask new issues if old ones are fixed in the same run.

2017-06-07 13:10 UTC, rock3r commented on app/src/main/java/net/squanchy/home/HomeActivity.java
> +                Timber.e("Unsupported proximity event: %s", proximityEvent);
Warnings don't go to he... erm, on Crashlytics.

2017-06-07 13:10 UTC, rock3r commented on app/src/main/java/net/squanchy/navigation/RoutingActivity.java
> +        subscriptions = new CompositeDisposable();
Yes it should 👍

2017-06-07 13:10 UTC, rock3r commented on app/src/main/java/net/squanchy/navigation/RoutingActivity.java
> +        subscriptions.dispose();
proooooooooobably yes 💃

2017-06-07 13:11 UTC, rock3r commented on app/src/main/java/net/squanchy/navigation/firststart/FirstStartWithNoNetworkActivity.java
> +@SuppressWarnings("PMD.ExcessiveImports")           // Might use some refactoring later on to extract some collaborator
same here, I'd rather not risk sneaking in new issues because of non-zero thresholds

2017-06-07 13:11 UTC, rock3r commented on app/src/main/java/net/squanchy/notification/NotificationsIntentService.java
> +        subscriptions = new CompositeDisposable();
I might have forgotten it :P

2017-06-07 13:12 UTC, rock3r commented on app/src/main/java/net/squanchy/proximity/preconditions/ModularProximityPreconditions.java
> +    @SuppressWarnings("PMD.UseVarargs") // This array is passed to the Android APIs and is kept for consistency
And that's relevant to this comment because...?

2017-06-07 13:12 UTC, rock3r commented on app/src/main/java/net/squanchy/schedule/domain/view/Event.kt
> +@Suppress("LongParameterList") // This is just a big model - TODO refactor this to split it up
Nope

2017-06-07 13:13 UTC, rock3r commented on app/src/main/java/net/squanchy/schedule/view/ScheduleViewPagerAdapter.java
> +        return date.toString(TITLE_FORMAT_TEMPLATE).toUpperCase(Locale.getDefault());
Those are for parsing, this is to format user-facing data, so it is correct, yes

2017-06-07 13:13 UTC, rock3r commented on app/src/main/java/net/squanchy/search/SearchActivity.java
> +@SuppressWarnings("PMD.ExcessiveImports")           // Might use some refactoring later on to extract some collaborator
Ditto

2017-06-07 13:13 UTC, rock3r commented on app/src/main/java/net/squanchy/speaker/domain/view/Speaker.kt
> +@Suppress("LongParameterList") // This is just a big model - TODO refactor this to split it up
Ditto

2017-06-07 13:14 UTC, rock3r commented on app/src/main/java/net/squanchy/support/widget/SpeakerView.java
> +    protected LayoutInflater layoutInflater() {
Dayum! Yes.

2017-06-07 13:14 UTC, rock3r commented on app/src/main/java/net/squanchy/support/view/Hotspot.java
> +    @SuppressWarnings("PMD.ShortMethodName") // Cannot really do much, this is a coordinate value
Yeah 💃

2017-06-07 13:15 UTC, rock3r commented on circle.yml
> +        FABRIC_API_KEY: 0000000000000000000000000000000000000000
No, this has to match (like all other env variables) the ones the build looks for, otherwise the secrets plugin won't find them

2017-06-07 13:15 UTC, fourlastor commented on app/src/main/java/net/squanchy/proximity/preconditions/ModularProximityPreconditions.java
> +    @SuppressWarnings("PMD.UseVarargs") // This array is passed to the Android APIs and is kept for consistency
I wouldn't see it as a big issue to have a varargs, not a blocker tho

2017-06-07 13:16 UTC, fourlastor commented on circle.yml
> +        FABRIC_API_KEY: 0000000000000000000000000000000000000000
Ah, bummer, no problem then

2017-06-07 13:19 UTC, rock3r commented on app/src/main/java/net/squanchy/notification/NotificationsIntentService.java
> +            subscriptions.add(
I wouldn't clear indiscriminately as every subscription is a separate notification and there might be multiple ones at the same time being prepared (e.g., multiple sessions in the same timeslot). Do they auto-unsubscribe when they complete?

2017-06-07 13:23 UTC, fourlastor commented on app/src/main/java/net/squanchy/notification/NotificationsIntentService.java
> +            subscriptions.add(
they do

2017-06-08 09:41 UTC, rock3r commented on app/src/main/java/net/squanchy/proximity/preconditions/ModularProximityPreconditions.java
> +    @SuppressWarnings("PMD.UseVarargs") // This array is passed to the Android APIs and is kept for consistency
It really looks weird to have it here and not on the other method which takes two consecutive `int[]`, as written in the comment I preferred consistency between the methods and with the system API they map to. I would not change it to a varargs at all _in this case_

2017-06-08 09:42 UTC, rock3r commented on app/src/main/java/net/squanchy/notification/NotificationsIntentService.java
> +            subscriptions.add(
Ok it's as I wanted it to be then, I don't think we should clear before the if. The `IntentService` will process intents sequentially, and we're not specifying an `observeOn()`, so it wouldn't make much of a difference. Still, I have put it in `onDestroy` which seems the best place for that (note that `IntentService` does not have `onStop`). See 8e172f5cf921b19408d3a311834bd02a9a677831

2017-06-08 09:42 UTC, rock3r commented on app/src/main/java/net/squanchy/notification/NotificationsIntentService.java
> +        subscriptions = new CompositeDisposable();
8e172f5cf921b19408d3a311834bd02a9a677831

2017-06-08 09:42 UTC, rock3r commented on app/src/main/java/net/squanchy/navigation/RoutingActivity.java
> +        subscriptions.dispose();
8841d6358cc4d73ffff4df40dd901cf2eef37953

2017-06-08 09:42 UTC, rock3r commented on app/src/main/java/net/squanchy/navigation/RoutingActivity.java
> +        subscriptions = new CompositeDisposable();
8841d6358cc4d73ffff4df40dd901cf2eef37953

2017-06-08 10:53 UTC, fourlastor commented
@rock3r great! just missing the `final` on the `protected` method :)

2017-06-08 10:55 UTC, rock3r commented on app/src/main/java/net/squanchy/support/widget/SpeakerView.java
> +    protected LayoutInflater layoutInflater() {
07d53fd310d5d7943941af56cac60b095bae40b3

2017-06-08 10:55 UTC, fourlastor approved these changes

2017-06-08 11:16 UTC, quiro91 approved these changes
👍

2017-06-08 11:16 UTC, merged