Update all the Android dependencies to v26 🎉
squanchy-dev/squanchy-android pull request #300
Opened 2017-07-25 17:04 UTC by rock3r

This PR updates the app to target Android O, use all the new 26-flavoured dependencies, updates Detekt to M13.2 and fixes a nasty bug in the Crashlytics init code.

2017-07-25 17:43 UTC, fourlastor requested changes
One question 💃

2017-07-25 17:43 UTC, fourlastor commented on team-props/static-analysis/detekt-config.yml
> +# *experimental feature*
hm are we using this?

2017-07-26 08:22 UTC, rock3r commented on team-props/static-analysis/detekt-config.yml
> +# *experimental feature*
No, I'm just merging in from the mainline ruleset because they keep changing quite fast. When the ruleset stabilises I'll make a cleanup pass.

2017-07-26 08:36 UTC, fourlastor approved these changes

2017-07-26 08:36 UTC, merged