Firestore/cleanup
squanchy-dev/squanchy-android pull request #475
Opened 2018-03-12 20:04 UTC by quiro91

## Problem

After moving from the RTD to Firestore there's a bunch of stuff we need to clean up a bit

## Solution

Clean it up. This is the first of two PRs to address this issue

### Paired with 

Nobody

2018-03-12 20:48 UTC, fourlastor requested changes
💯 for the changes, only 2 major points:

- interfaces should stay where they belong, implementation agnostic, not in the firestore package
- firebase is a service provider that offers firestore and rtdb as services, I think the package `firebase` is more appropriate, (firebase firestore, firebase authentication, etc..)

2018-03-12 20:48 UTC, fourlastor commented on app/src/main/java/net/squanchy/eventdetails/EventDetailsService.kt
> +import net.squanchy.service.firestore.FirebaseAuthService
this isn't firestore specific

2018-03-12 20:48 UTC, fourlastor commented on app/src/main/java/net/squanchy/eventdetails/EventDetailsService.kt
> +import net.squanchy.service.repository.firestore.EventRepository
this isn't firestore specific

2018-03-12 20:48 UTC, fourlastor commented on app/src/main/java/net/squanchy/home/HomeComponent.kt
> +internal fun homeComponent(activity: AppCompatActivity) =
let's drop `internal`

2018-03-12 20:48 UTC, fourlastor commented on app/src/main/java/net/squanchy/schedule/ScheduleComponent.kt
> +import net.squanchy.service.repository.firestore.TracksRepository
this one isn't firestore specific

2018-03-12 20:48 UTC, fourlastor commented on app/src/main/java/net/squanchy/service/firestore/injection/FirestoreModule.kt
>  class FirestoreModule {
probably the best thing is to have everything inside a `firebase` package (which is the 3rd party offering the services) and then we'll have `FirestoreDbService` (which is the particular firebase service we're using)

2018-03-12 20:48 UTC, fourlastor commented on app/src/main/java/net/squanchy/service/repository/firestore/FirestoreEventRepository.kt
> +interface EventRepository {
:x: those interface shouldn't be in `firestore`

2018-03-12 23:55 UTC, quiro91 commented
@fourlastor back to review

2018-03-13 08:00 UTC, fourlastor approved these changes

2018-03-13 08:00 UTC, merged