Wifi configuration
squanchy-dev/squanchy-android pull request #529
Opened 2018-04-09 09:21 UTC by danybony

## Problem

We want to allow the user to automatically configure the conference wifi

## Solution

I used Firebase Remote config to get the feature details (feature enabled/disabled, ssid, password).
If the feature is enabled, we show a new preference in the app settings. To avoid a flickering of that preference in case of feature disabled (we remove it in that case) I choose to fetch the remote config boolean immediately, instead of using `RemoteConfig#getBoolean` (which will fetch updated values and asynchronously emit the actual boolean).

When the user clicks on the preference, we attempt to set the wifi immediately. In case off success, a snackbar with the success message is shown, otherwise we navigate to the wifi config error screen.

**Note**: the layout for this screen needs to be tweaked, as I couldn't match the design using a constraint layout.

In that screen the user can see the network details, copy the password to the clipboard and navigate to the system wifi settings to enter it manually.

#### TODO:
Add analytics

### Test(s) added

No

### Screenshots

 App settings with config success | Error screen | Error screen with password copied message (layout not updated, it's just to show the toast)
 ------ | ----- | -----
![device-2018-04-09-110558](https://user-images.githubusercontent.com/3942812/38489794-b0947f92-3be7-11e8-9c1b-529b5ada86c3.png) | ![image](https://user-images.githubusercontent.com/3942812/38665018-99e6407c-3e3b-11e8-99c0-f4c91b466691.png) | ![device-2018-04-09-101337](https://user-images.githubusercontent.com/3942812/38489813-c11167f4-3be7-11e8-89f1-f262e95861bc.png)

### Paired with

Nobody

2018-04-09 16:15 UTC, rock3r requested changes
Couple of notes, and waiting to get the finalised layout/styles

2018-04-09 16:15 UTC, rock3r commented on app/src/main/java/net/squanchy/remoteconfig/RemoteConfig.kt
> +    fun wifiSsid(): String = firebaseRemoteConfig.getString(KEY_WIFI_SSID)
Why not returning a `data class WifiConfiguration(ssid: String, password: String)` for better typing? Would work especially well if you also moved these to a specialised function in the `remoteconfig` package that gets in the `RemoteConfig` instance and avoids having feature-specific constants and methods on `RemoteConfig`, which is supposed to be a feature-agnostic entry point.

```kotlin
internal fun obtainVenueWifiConfiguration(remoteConfig: RemoteConfig): WifiConfiguration? = ...

data class WifiConfiguration(ssid: String, password: String)
```

2018-04-09 16:15 UTC, rock3r commented on app/src/main/java/net/squanchy/settings/SettingsFragment.kt
> +    private fun setupWifi() {
This should really be moved to a collaborator

2018-04-09 16:15 UTC, rock3r commented on app/src/main/res/values/strings.xml
> +  <string name="wifi_config_error_title">Oh… uh, it didn\'t work</string>
You could use a proper apostrophe and avoid the escape = `’` vs `'`

2018-04-12 08:22 UTC, danybony commented on app/src/main/res/values/strings.xml
> +  <string name="wifi_config_error_title">Oh… uh, it didn\'t work</string>
https://github.com/squanchy-dev/squanchy-android/pull/529/commits/986c6bf32b6175365425dc462287bb3d5699f5f3

2018-04-12 08:23 UTC, danybony commented on app/src/main/java/net/squanchy/remoteconfig/RemoteConfig.kt
> +    fun wifiSsid(): String = firebaseRemoteConfig.getString(KEY_WIFI_SSID)
https://github.com/squanchy-dev/squanchy-android/pull/529/commits/c29c90ee977defd9cab98be44f2a70761895e019

2018-04-12 08:23 UTC, danybony commented on app/src/main/java/net/squanchy/settings/SettingsFragment.kt
> +    private fun setupWifi() {
https://github.com/squanchy-dev/squanchy-android/pull/529/commits/149c9fc9646b6a5133e13894202c914bcf0a150b

2018-04-12 08:29 UTC, rock3r approved these changes
Nice one, thanks Danielo! :shipit:

2018-04-12 08:29 UTC, merged