Update CircleCI config to 2.1
squanchy-dev/squanchy-android pull request #623
Opened 2019-03-17 15:33 UTC by fourlastor

## Problem

We were still using CircleCI config v 2.0

## Solution

Enable https://circleci.com/docs/2.0/build-processing/ (no drawbacks affecting us)
Update config file with the new settings

The benefit of this is that

1. Simple to read (executor tells you which executor you're using, steps are now named)
2. We can have a step that will in the future represent multiple steps (for example, I did it in this PR for the restore/save of gradle caches)

I changed the restore/save of gradle caches. The reason for that is that we don't want to invalidate the wrapper cache if our dependencies change, and vice versa. Also, the wrapper checksum wasn't part of the cache key, meaning updating our gradle wrapper wouldn't have created a new cache (caches are read-only, if a cache with the same name already exists, it won't be overwritten by the new value)

2019-03-17 15:36 UTC, fourlastor commented on .circleci/config.yml
> +  restore_gradle_cache:
This command now has 2 steps

2019-03-17 15:36 UTC, fourlastor commented on .circleci/config.yml
> +  save_gradle_cache:
This command now has 2 steps

2019-03-18 08:05 UTC, rock3r approved these changes
Noiceeee 💯 just a tiny bit about comments then good to go, thanks! :)

2019-03-18 08:05 UTC, rock3r commented on .circleci/config.yml
>    # Build Tools cache aliases
Here and in the following comments, I suppose they aren't aliases but commands now?

2019-03-18 08:24 UTC, rock3r commented
Question about CI timings tho...

This is what I'm seeing now:

 Run # | Run timings | Run total time
 --- | --- | ---
 [1](https://circleci.com/workflow-run/52a113be-f2b9-49a0-993f-dab47956da7b) | ![image](https://user-images.githubusercontent.com/153802/54516308-c60cec80-495e-11e9-8b88-69b9b760b39f.png) | 10:23
 [2](https://circleci.com/workflow-run/ae8fa26d-ab56-40b8-af9b-da59587bbdeb) | ![image](https://user-images.githubusercontent.com/153802/54516527-73800000-495f-11e9-989a-2a361904b27b.png) | 08:48
 [Before](url) | ![image](https://user-images.githubusercontent.com/153802/54516484-564b3180-495f-11e9-8152-7dae4d970627.png) | 4:16 (typical: ~5')

Looks like executing things is taking double the time now. Would you mind checking what the issue is and what's causing the regression, as everything else is the same as the "before" reference build?

2019-03-18 08:24 UTC, rock3r requested changes
Blocking until we figure out the timings regression

2019-03-20 10:39 UTC, fourlastor commented
Seems like it was a fluke, we tried re-running the workflow and it took 3 minutes and half when cached, so actually some saving in there :tada:!

2019-03-20 10:39 UTC, rock3r commented
Awesome, thanks for the work <3

2019-03-20 10:39 UTC, rock3r approved these changes

2019-03-20 10:39 UTC, merged