Sq 48/create bottom bar
squanchy-dev/squanchy-android pull request #85
Opened 2017-02-21 17:40 UTC by quiro91

This PR removes everything NavigationDrawer related and add a BottomNavigationView. The ScheduleActivity has been incorporated into the ScheduleView

2017-02-21 18:11 UTC, rock3r requested changes
One blocker and a bunch of comments

2017-02-21 18:11 UTC, rock3r commented on app/src/main/AndroidManifest.xml
> +    <activity android:name=".navigation.BottomNavigationActivity">
Use fully qualified name please

2017-02-21 18:11 UTC, rock3r commented on app/src/main/java/net/squanchy/navigation/BottomNavigationActivity.java
> +        BottomNavigationHelper.disableShiftMode(bottomNavigationView);
![](https://media.giphy.com/media/EAOPeZPjv3vMI/giphy.gif)

2017-02-21 18:11 UTC, rock3r commented on app/src/main/java/net/squanchy/navigation/BottomNavigationActivity.java
> +
Why all these whitelines? Are they missing TODOs?

2017-02-21 18:11 UTC, rock3r commented on app/src/main/java/net/squanchy/navigation/BottomNavigationHelper.java
> +    static void disableShiftMode(BottomNavigationView view) {
Should we open a feature request for this? :P

2017-02-21 18:11 UTC, rock3r commented on app/src/main/java/net/squanchy/navigation/view/BottomNavigationPagerAdapter.java
> +        return null;
I'd rather throw in this case, better than risking to fail silently

2017-02-21 18:11 UTC, rock3r commented on app/src/main/java/net/squanchy/navigation/view/BottomNavigationPagerAdapter.java
> +    private final Context context;
Empty line before this

2017-02-21 18:11 UTC, rock3r commented on app/src/main/java/net/squanchy/navigation/view/BottomNavigationPagerAdapter.java
> +    private static final int SCHEDULE_POSITION = 0;
This could be an `@IntDef`, would help if you use a `switch` in `createView()` too

2017-02-21 18:11 UTC, rock3r commented on app/src/main/java/net/squanchy/navigation/view/BottomNavigationPagerAdapter.java
> +        return 1;
Should probably be a constant

2017-02-21 18:11 UTC, rock3r commented on app/src/main/java/net/squanchy/navigation/view/NoSwipeViewPager.java
> +public class NoSwipeViewPager extends ViewPager {
❌  this is not preventing keyboard navigation, you need to override another method. Off the top of my head:

```java
@Override
public boolean executeKeyEvent(KeyEvent e) {
  return false;
}
```

2017-02-21 18:11 UTC, rock3r commented on app/src/main/java/net/squanchy/schedule/ScheduleModule.java
> +    ScheduleModule() {
You can remove this?

2017-02-21 18:11 UTC, rock3r commented on app/src/main/java/net/squanchy/schedule/ScheduleService.java
> +public class ScheduleService {
I think this doesn't need to be public

2017-02-21 18:11 UTC, rock3r commented on app/src/main/java/net/squanchy/schedule/ScheduleView.java
> +    public static ScheduleView inflate(Context context, ViewGroup parent) {
I really really dislike this being here. Can you put it in a `BottomTabsPagesFactory` of some sort instead, that you can use in the adapter to inflate the views?

2017-02-21 18:11 UTC, rock3r commented on app/src/main/res/drawable/ic_favourites_default.xml
> +        android:fillColor="#FFFFFF"
We should eventually use the attributes (e.g., `?colorControlNormal` here)

2017-02-21 18:11 UTC, rock3r commented on app/src/main/res/layout/activity_bottom_navigation.xml
> +<RelativeLayout xmlns:android="http://schemas.android.com/apk/res/android"
This should be a LinearLayout with the viewpager with a weight of 1 as height, seems easier to read (perf-wise it's the same)

2017-02-21 18:11 UTC, rock3r commented on app/src/main/res/menu/bottom_bar_menu.xml
> +</menu>
Missing empty line

2017-02-21 18:11 UTC, rock3r commented on app/src/main/res/menu/bottom_bar_menu.xml
> +  <item
Can you add empty lines around the items?

2017-02-21 18:24 UTC, tiwiz commented on app/src/main/java/net/squanchy/navigation/BottomNavigationHelper.java
> +    static void disableShiftMode(BottomNavigationView view) {
Or we open a PR 😁 I would add it to the list of things we can make better in there...

2017-02-22 08:46 UTC, rock3r commented on app/src/main/java/net/squanchy/navigation/BottomNavigationActivity.java
> +        NoSwipeViewPager viewPager = (NoSwipeViewPager) findViewById(R.id.main_view_pager);
You could've left `ViewPager` here but ¯\\\_(ツ)\_/¯

2017-02-22 08:46 UTC, rock3r commented on app/src/main/java/net/squanchy/navigation/view/BottomTabsPagesFactory.java
> +        switch (position){
cmd-alt-l

2017-02-22 08:46 UTC, rock3r commented on app/src/main/java/net/squanchy/navigation/view/BottomTabsPagesFactory.java
> +        throw new IllegalArgumentException("Invalid position");
Why outside of the `switch`? It should be in the `default` branch (which in this case you can leave collapsed with the unhandled cases). Also maybe a more informative message such as `Unsupported tab type for position n` could help

2017-02-22 08:46 UTC, rock3r commented on app/src/main/java/net/squanchy/navigation/view/Tab.java
> +@interface Tab {
💯

2017-02-22 08:46 UTC, rock3r commented on app/src/main/java/net/squanchy/navigation/view/Tab.java
> +        BottomNavigationPagerAdapter.VENUE_POSITION})
cmd-alt-l

2017-02-22 08:46 UTC, rock3r commented on app/src/main/java/net/squanchy/navigation/view/BottomNavigationPagerAdapter.java
> +    public static final int SCHEDULE_POSITION = 0;
Maybe these could be moved to `Tab`? Or you could move `Tab` here and make these private?

2017-02-22 08:53 UTC, quiro91 commented on app/src/main/java/net/squanchy/navigation/view/BottomNavigationPagerAdapter.java
> +    public static final int SCHEDULE_POSITION = 0;
We would still need the positions to be public because they are used in the BottomNavigationActivity

2017-02-22 09:02 UTC, rock3r commented on app/src/main/java/net/squanchy/navigation/view/BottomNavigationPagerAdapter.java
> +    public static final int SCHEDULE_POSITION = 0;
Ok, nevermind then for now

2017-02-22 09:15 UTC, rock3r approved these changes
Nice!

2017-02-22 09:21 UTC, rock3r commented
Let me close and reopen, GH is missing that Travis completed the build

2017-02-22 09:30 UTC, merged