Add image loader
squanchy-dev/squanchy-android pull request #90
Opened 2017-02-22 17:27 UTC by rock3r

This PR:
 * Bumps Firebase/Play Services from 10.0.1 to 10.2.0
 * Adds Glide, Glide-OkHttp3, and FirebaseUI-storage dependencies
 * Defines the `ImageLoader` interface, and its Glide-powered implementation
 * Injects and uses the `ImageLoader` to load speaker photos (dummy for now, we don't have that data yet)

 Before | After
 --- | --- 
 ![image](https://cloud.githubusercontent.com/assets/153802/23223878/8fc81e30-f92c-11e6-8db2-2220340f3db8.png) | ![image](https://cloud.githubusercontent.com/assets/153802/23223280/e53913ee-f92a-11e6-9283-ed47d98fe0b9.png)

2017-02-22 19:35 UTC, fourlastor requested changes
That's cool! But we need to clear up a bit the dependency graph :dancer:

2017-02-22 19:35 UTC, fourlastor commented on app/src/main/java/net/squanchy/imageloader/GlideImageLoader.java
> +                    .using(new FirebaseImageLoader())
do we need a new `FirebaseImageLoader` for every request? we could have this in the constructor and initialized once only when we create `GlideImageLoader` instead (unless it's meant to be use and throw away)

2017-02-22 19:35 UTC, fourlastor commented on app/src/main/java/net/squanchy/imageloader/GlideImageLoader.java
> +            return Glide.with(context);
this also imho should be moved as a dependency and passed instead of the context by `GlideImagerLoader`, which gets it passed by the object graph.

2017-02-22 19:35 UTC, fourlastor commented on app/src/main/java/net/squanchy/imageloader/ImageLoaderModule.java
> +    ImageLoader imageLoader() {
here you would have `imageLoader(Glide glide)` and a `@Provides Glide glide() { return Glide.with(context); }`

2017-02-22 19:35 UTC, fourlastor commented on app/src/main/java/net/squanchy/imageloader/ImageLoaderComponent.java
> +@ActivityLifecycle
are we sure we want this to be activity specific? I would see this as a component shared across the app. I'm ok to move it when we use it in another activity tho.

2017-02-22 19:41 UTC, fourlastor commented on app/src/main/java/net/squanchy/schedule/view/SpeakerView.java
> +        imageLoader = ImageLoaderInjector.obtain(context).imageLoader();
This means every instance of `SpeakerView` will have a new instance of `ImageLoaderComponent`, `ImageLoader` and so on, are we sure that's what you meant to do?

2017-02-23 08:16 UTC, rock3r commented on app/src/main/java/net/squanchy/imageloader/GlideImageLoader.java
> +            return Glide.with(context);
Didn't think about that, good idea

2017-02-23 08:18 UTC, rock3r commented on app/src/main/java/net/squanchy/imageloader/GlideImageLoader.java
> +                    .using(new FirebaseImageLoader())
[It seems](https://github.com/firebase/FirebaseUI-Android/blob/master/storage/src/main/java/com/firebase/ui/storage/images/FirebaseImageLoader.java it's pretty much a fire-and-forget thing, this is also how the documentation shows it being used. I thought about storing it in a field but the init does almost nothing and you aren't firing thousands of requests all at the same time, so... ¯\\\_(ツ)\_/¯

2017-02-23 08:19 UTC, rock3r commented on app/src/main/java/net/squanchy/imageloader/ImageLoaderComponent.java
> +@ActivityLifecycle
It takes a Context, seems the logical thing to do to avoid leaks (and no, I don't think it should be an Application Context)

2017-02-23 08:20 UTC, rock3r commented on app/src/main/java/net/squanchy/schedule/view/SpeakerView.java
> +        imageLoader = ImageLoaderInjector.obtain(context).imageLoader();
Seems reasonable given there's going to be a handful of those only (only that many cards you can fit on the screen, and it's in a recyclerview, so there's going to be less than ten). Thought it'd be ok as first draft. Up for improving tho.

2017-02-23 09:00 UTC, rock3r commented on app/src/main/java/net/squanchy/imageloader/ImageLoaderModule.java
> +    ImageLoader imageLoader() {
822c089d73540ff08fe4bbf83c43c9a201b15776

Fun fact `Glide.with(context)` returns `RequestManager` not `Glide` for some reason

2017-02-23 09:01 UTC, rock3r commented on app/src/main/java/net/squanchy/imageloader/GlideImageLoader.java
> +            return Glide.with(context);
822c089d73540ff08fe4bbf83c43c9a201b15776

2017-02-23 09:03 UTC, rock3r commented
Closing and reopening to see if Travis works now

2017-02-23 13:19 UTC, fourlastor approved these changes

2017-02-23 14:20 UTC, merged